---
abstract: "Helper functions for managing Honeydew's external services"
author:
  - 'Daniel Gempesaw <gempesaw@gmail.com>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  Test::Deep: '0'
  Test::Spec: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Honeydew-ExternalServices
requires:
  Cwd: '0'
  Exporter: '0'
  File::Basename: '0'
  POSIX: '0'
  feature: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/honeydew-sc/Honeydew-ExternalServices/issues
  homepage: https://github.com/honeydew-sc/Honeydew-ExternalServices
  repository: https://github.com/honeydew-sc/Honeydew-ExternalServices.git
version: '0.03'
